[server]
bind_addr = "0.0.0.0:2333"
default_token = "ETH_Node"

[client.services.30303]
bind_addr = "0.0.0.0:30303"


[server.services.tcp13000]
type = "tcp"
bind_addr = "0.0.0.0:13000"

[server.services.udp12000]
bind_addr = "0.0.0.0:12000"

